#server:
#  port: 8080
#spring:
#  application:
#    name: ms-accounts
#  datasource:
##    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:./data/msaccounts
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      path: /h2-console
#      enabled: true
#  sql:
#    init:
#      mode: never
#      schema-locations: classpath:db/schema.sql
##      data-locations: classpath:db/data.sql

# Configuration is delegated to config-server
#Config n1
#spring.config.import=optional:configserver:http://localhost:8888
#spring.cloud.config.name=msaccounts

# Choose configuration file from BankApplication_Config
spring:
  application:
    name: ms-accounts
  config:
    import:
      configserver:http://localhost:8888/

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
    instances:
      detailsForCustomerSupportApp:
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          15000
        permitted-number-of-calls-in-half-open-state: 2
  retry:
    instances:
      retryForCustomerDetails:
        max-attempts: 1
        wait-duration:
          seconds: 2
  ratelimiter:
    configs:
      default:
        register-health-indicator: true
    instances:
      sayHello:
        timeout-duration:
          seconds: 5
        limit-refresh-period:
          seconds: 5
        limit-for-period: 1