## First Version - configuration files in the configserver microservice, internal path
#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/configuration
#  profiles:
#    active: native
#server:
#  port: 8888


#Config Git -- Environment Variables are set in IntelliJ or Bash (export $GIT_USERNAME= XXXX // Same for Password)
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
          default-label: master
  profiles:
    active: git
#    active: git, native
logging:
  level:
    org:
      springframework:
        cloud:
          config:
            server:
              environment: TRACE