## First Version - configuration files in the configserver microservice, internal path
#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/configuration
#  profiles:
#    active: native
#server:
#  port: 8888

#Config Git
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JRoullet/Bankapplication_config.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
          default-label: master
#  profiles:
#    active: native
